"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { X, Download, Upload, CheckCircle2, FileSpreadsheet } from "lucide-react";
import { Button } from "@/shared/ui/button";
import * as XLSX from "xlsx";
import type { CurrentUser } from "@/entities/user/model/types";
import type { AssignableRole, BulkCreateEmployeeResult } from "@/features/employees/types/employee";
import { getAssignableRoles } from "@/features/employees/utils/permissions";
import { useBulkCreateEmployeesMutation } from "@/features/employees/hooks/useEmployeeMutations";
import { getNextEmployeeId } from "@/features/employees/api/employeeService";
import { ConfirmDialog } from "@/features/employees/components/ConfirmDialog";

interface BulkCreateEmployeeModalProps {
  open: boolean;
  onClose: () => void;
  currentUser: CurrentUser | null;
}

interface DraftRow {
  employee_id: string;
  name: string;
  role: AssignableRole;
  password: string;
  isAutoGeneratedId?: boolean;
}

function generateRandomPassword(length = 10): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let password = "";
  for (let i = 0; i < length; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}

export function BulkCreateEmployeeModal({ open, onClose, currentUser }: BulkCreateEmployeeModalProps) {
  const assignableRoles = getAssignableRoles(currentUser);
  
  const [rows, setRows] = useState<DraftRow[]>([]);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [results, setResults] = useState<(BulkCreateEmployeeResult & { password?: string, name?: string })[] | null>(null);
  
  const fileInputRef = useRef<HTMLInputElement>(null);
  const mutation = useBulkCreateEmployeesMutation();

  const resetState = useCallback(() => {
    setRows([]);
    setValidationError(null);
    setConfirmOpen(false);
    setResults(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  }, []);

  const handleClose = useCallback(() => {
    resetState();
    onClose();
  }, [resetState, onClose]);

  useEffect(() => {
    if (!open) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") handleClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [open, handleClose]);

  if (!open) return null;

  const downloadTemplate = () => {
    const ws = XLSX.utils.aoa_to_sheet([
      ["사번(비워두면 자동부여)", "이름(필수)", "역할(ADMIN/WORKER/GUEST 중 택1)"],
      ["", "홍길동", "WORKER"],
      ["WM9999001", "김철수", "ADMIN"],
    ]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "직원등록양식");
    XLSX.writeFile(wb, "직원_일괄등록_양식.xlsx");
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setValidationError(null);
    setResults(null);

    const reader = new FileReader();
    reader.onload = async (evt) => {
      try {
        const bstr = evt.target?.result;
        const wb = XLSX.read(bstr, { type: "binary" });
        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];
        const data = XLSX.utils.sheet_to_json(ws, { header: 1 }) as string[][];

        if (data.length <= 1) {
          setValidationError("데이터가 없습니다. 양식에 맞게 입력해주세요.");
          return;
        }

        
        const parsedRows: DraftRow[] = [];
        let missingNamesCount = 0;
        let invalidRolesCount = 0;

        // 사번을 채우기 위해 백엔드에서 다음 사번 가져오기
        let nextPrefix = "WM";
        let nextSeq = 1;
        try {
          const idData = await getNextEmployeeId();
          const baseId = idData.next_employee_id; // e.g. WM2608001
          nextPrefix = baseId.slice(0, 6); // WM2607
          nextSeq = parseInt(baseId.slice(6), 10);
        } catch (err) {
          console.error("Failed to fetch next employee id", err);
        }

        for (let i = 1; i < data.length; i++) {
          const row = data[i];
          if (!row || row.length === 0 || (!row[0] && !row[1] && !row[2])) continue; // 빈 행 무시

          let empId = (row[0] || "").toString().trim();
          let isAuto = false;
          if (!empId) {
            empId = `${nextPrefix}${String(nextSeq).padStart(3, "0")}`;
            nextSeq++;
            isAuto = true;
          }

          const name = (row[1] || "").toString().trim();
          if (!name) missingNamesCount++;

          const rawRole = (row[2] || "").toString().trim().toUpperCase();
          let role: AssignableRole = "WORKER";
          if (assignableRoles.includes(rawRole as AssignableRole)) {
            role = rawRole as AssignableRole;
          } else {
            if (rawRole) invalidRolesCount++;
          }

          parsedRows.push({
            employee_id: empId,
            name,
            role,
            password: generateRandomPassword(),
            isAutoGeneratedId: isAuto,
          });
        }

        if (missingNamesCount > 0) {
          setValidationError(`이름이 누락된 행이 ${missingNamesCount}개 있습니다.`);
          return;
        }
        if (invalidRolesCount > 0) {
          setValidationError(`잘못된 역할이 입력된 행이 ${invalidRolesCount}개 있습니다. (ADMIN, WORKER, GUEST 중 하나여야 합니다)`);
          return;
        }
        
        if (parsedRows.length === 0) {
          setValidationError("유효한 데이터가 없습니다.");
          return;
        }

        setRows(parsedRows);
        if (fileInputRef.current) fileInputRef.current.value = ""; // 초기화
      } catch {
        setValidationError("엑셀 파일을 읽는 중 오류가 발생했습니다.");
      }
    };
    reader.readAsBinaryString(file);
  };

  const handleConfirmSubmit = () => {
    mutation.mutate(
      { employees: rows.map(({ employee_id, name, role, password }) => ({ employee_id, name, role, password })) },
      {
        onSuccess: (data) => {
          // 원래 rows와 매핑하여 비밀번호 유지
          const mergedResults = data.results.map((r) => {
            const originalRow = rows.find((dr) => dr.employee_id === r.employee_id);
            return {
              ...r,
              name: originalRow?.name,
              password: originalRow?.password,
            };
          });
          setResults(mergedResults);
          setConfirmOpen(false);
          setRows([]);
        },
        onError: () => {
          setConfirmOpen(false);
        },
      }
    );
  };

  const downloadResults = () => {
    if (!results) return;
    
    const exportData = results.map((r) => ({
      "사번": r.employee_id,
      "이름": r.name || "",
      "결과": r.success ? "성공" : `실패: ${r.reason}`,
      "초기 비밀번호": r.success ? r.password : "",
    }));

    const ws = XLSX.utils.json_to_sheet(exportData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "생성결과");
    XLSX.writeFile(wb, "직원_계정_생성_결과.xlsx");
  };

  return (
    <>
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4" onClick={handleClose}>
      <div
        className="bg-white dark:bg-gray-900 rounded-2xl shadow-xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 dark:border-gray-800">
          <h3 className="text-base font-bold text-gray-800 dark:text-gray-100">엑셀 일괄 등록</h3>
          <button
            type="button"
            onClick={handleClose}
            className="p-1.5 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-400 dark:text-gray-500 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 overflow-y-auto flex-1 space-y-6">
          {!results && (
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex-1 bg-blue-50 border border-blue-100 p-4 rounded-xl space-y-3">
                <h4 className="font-semibold text-blue-900 flex items-center">
                  <FileSpreadsheet className="w-4 h-4 mr-2" />
                  1. 엑셀 양식 다운로드
                </h4>
                <p className="text-sm text-blue-700">
                  직원 정보를 입력할 수 있는 엑셀 양식을 다운로드합니다.<br/>
                  사번을 비워두면 시스템이 자동으로 순차 부여합니다.
                </p>
                <Button variant="outline" className="w-full bg-white dark:bg-gray-900" onClick={downloadTemplate}>
                  <Download className="w-4 h-4 mr-2" />
                  양식 다운로드
                </Button>
              </div>
              <div className="flex-1 bg-gray-50 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700 p-4 rounded-xl space-y-3">
                <h4 className="font-semibold text-gray-900 dark:text-gray-100 flex items-center">
                  <Upload className="w-4 h-4 mr-2" />
                  2. 작성된 엑셀 업로드
                </h4>
                <p className="text-sm text-gray-600 dark:text-gray-300">
                  작성하신 엑셀 파일을 업로드하면 데이터를 검증하고 미리보기를 제공합니다.
                </p>
                <div>
                  <input
                    type="file"
                    accept=".xlsx, .xls"
                    className="hidden"
                    ref={fileInputRef}
                    onChange={handleFileUpload}
                  />
                  <Button className="w-full" onClick={() => fileInputRef.current?.click()}>
                    <Upload className="w-4 h-4 mr-2" />
                    엑셀 업로드
                  </Button>
                </div>
              </div>
            </div>
          )}

          {validationError && (
            <div className="p-3 bg-red-50 border border-red-100 rounded-lg text-sm text-red-600">
              {validationError}
            </div>
          )}

          {mutation.isError && (
            <p className="text-sm text-red-600 bg-red-50 p-3 rounded-lg">
              생성 요청에 실패했습니다. 네트워크 상태를 확인하거나 잠시 후 다시 시도해 주세요.
            </p>
          )}

          {rows.length > 0 && !results && (
            <div className="space-y-3 border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden">
              <div className="bg-gray-100 dark:bg-gray-800 px-4 py-2 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
                <h4 className="font-semibold text-sm text-gray-700 dark:text-gray-300">업로드 데이터 미리보기</h4>
                <span className="text-xs text-gray-500 dark:text-gray-400">총 {rows.length}명</span>
              </div>
              <div className="max-h-64 overflow-y-auto px-4 pb-4">
                <table className="w-full text-sm text-left">
                  <thead>
                    <tr className="text-gray-500 dark:text-gray-400 border-b border-gray-100 dark:border-gray-800">
                      <th className="py-2 font-medium">사번</th>
                      <th className="py-2 font-medium">이름</th>
                      <th className="py-2 font-medium">역할</th>
                      <th className="py-2 font-medium text-gray-400 dark:text-gray-500">비밀번호</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((row, i) => (
                      <tr key={i} className="border-b border-gray-50 dark:border-gray-800/60 last:border-0">
                        <td className="py-2">
                          {row.employee_id}
                          {row.isAutoGeneratedId && <span className="ml-2 text-[10px] bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">자동생성</span>}
                        </td>
                        <td className="py-2 font-medium">{row.name}</td>
                        <td className="py-2">{row.role}</td>
                        <td className="py-2 text-gray-400 dark:text-gray-500 font-mono text-xs">{"*".repeat(8)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {results && (
            <div className="space-y-4">
              <div className="flex items-center justify-center p-4 bg-green-50 rounded-lg border border-green-100">
                <CheckCircle2 className="w-6 h-6 text-green-500 mr-2" />
                <p className="text-sm font-medium text-green-800">
                  총 {results.length}건 중 {results.filter(r => r.success).length}건 성공
                </p>
              </div>

              <div className="p-4 bg-gray-50 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700 rounded-xl space-y-3">
                <div className="flex justify-between items-center mb-2">
                  <h4 className="font-semibold text-sm text-gray-700 dark:text-gray-300">초기 비밀번호 다운로드</h4>
                  <Button size="sm" onClick={downloadResults}>
                    <Download className="w-4 h-4 mr-2" />
                    결과 엑셀 다운로드
                  </Button>
                </div>
                <p className="text-xs text-orange-600">
                  * 성공한 계정의 <strong>초기 비밀번호</strong>가 포함되어 있습니다. 반드시 다운로드하여 직원들에게 안전하게 전달해 주세요. 창을 닫으면 다시 조회할 수 없습니다.
                </p>
              </div>

              <div className="max-h-64 overflow-y-auto border border-gray-200 dark:border-gray-700 rounded-lg p-3">
                {results.map((result, idx) => (
                  <div key={idx} className="flex justify-between items-center py-2 border-b border-gray-50 dark:border-gray-800/60 last:border-0 text-sm">
                    <div>
                      <span className="font-medium mr-2">{result.employee_id}</span>
                      <span className="text-gray-500 dark:text-gray-400">{result.name}</span>
                    </div>
                    {result.success ? (
                      <span className="text-green-600 font-medium">생성 완료</span>
                    ) : (
                      <span className="text-red-600">{result.reason}</span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="flex flex-col-reverse gap-2 border-t border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/60 p-4 sm:flex-row sm:justify-end">
          <Button type="button" variant="outline" onClick={handleClose}>
            닫기
          </Button>
          {!results && rows.length > 0 && (
            <Button type="button" onClick={() => setConfirmOpen(true)} disabled={mutation.isPending}>
              {mutation.isPending ? "처리 중..." : "일괄 생성하기"}
            </Button>
          )}
        </div>
      </div>
    </div>

    <ConfirmDialog
      open={confirmOpen}
      title={`총 ${rows.length}명의 직원 계정을 생성할까요?`}
      description="사번과 비밀번호가 자동으로 부여되며, 계정 생성 후에는 초기 비밀번호를 화면에서만 다운로드할 수 있습니다."
      isLoading={mutation.isPending}
      onConfirm={handleConfirmSubmit}
      onCancel={() => setConfirmOpen(false)}
    />
    </>
  );
}
